### ISSUE TITLE
Sending RTP packets from nodejs client to browser does not work

### ISSUE THREAD

**Issue by SkorpyoN95** [shinyoshiaki/werift-webrtc#114]
Hi!

I'm trying to send RTP packets from NodeJS client using werift-webrtc, to browser client using browser webrtc API. My code is basically the same as in [sendonly example](https://github.com/shinyoshiaki/werift-webrtc/blob/develop/examples/mediachannel/sendonly/offer.ts), the only difference is I spawn ffmpeg process instead of gstreamer.

I was testing the code with Brave (chromium), Firefox and Edge and for none of them sending video worked. I also checked webrtc-internal page and in statistics I noticed that RTP packets were received and all of them were lost.

Sending video worked, when the other client was another NodeJS client and not a browser one.

What do I need to do to send video to browser? Or maybe is it not possible at the moment?

**Comment by shinyoshiaki** [comment]
Added FFmpeg example. Please try this
https://github.com/shinyoshiaki/werift-webrtc/commit/8d7381ff4d863a3db02c69bb633c3e331cdcdc1a

**Comment by SkorpyoN95** [comment]
Thanks for your reply.

Unfortunately, this doesn't change anything. Still no video on browser side. I would like to emphasize, that on browser side I use browser [WebRTC API](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API). Is that API and the library not compatible?

I can receive RTP sent from browser to NodeJS client.
I can also send it back by replacing tracks in transceiver (like in sendrecv example).
But I'm not able to send my own video from ffmpeg.

**Comment by shinyoshiaki** [comment]
In my environment, the sample program FFmpeg test source plays in Chrome without any problems.

First of all, please tell me if this sample app works.

### How to start the sample application

**server side**

```sh
yarn ts-node examples/mediachannel/sendonly/ffmpeg.ts
```

**client side**

```sh
npx http-server -o ./examples/mediachannel/sendonly/answer.html
```

**Comment by SkorpyoN95** [comment]
In my environment, peers couldn't connect. I use Windows and due to ffmpeg, I run code in Docker; probably networking issues there. I had someone run your sample and my code on Linux machine and they both work perfectly.

What suprises me, when I serve html via my IDE (IntelliJ) peers can connect but cannot transmit RTPs...

Anyway, the issue seems to be with my environment, not with your library.
Thanks for your time and for this awesome library!
Cheers!

**Comment by shinyoshiaki** [comment]
I'll try to check the problem in Windows machine when I have time.

**Comment by SkorpyoN95** [comment]
By the way, have you ever tried to connect to Jitsi conference? When I connect to Jitsi Videobridge, it doesn't relay sources from other participants to me and I'm wondering if I do something wrong with setup. The only track I get is the one owned by Videobridge. I tried to connect like in recvonly example, also tried with simulcast one.

**Comment by shinyoshiaki** [comment]
If you provide the source code to connect to that "Jitsi conference", I'll debug it.

**Comment by SkorpyoN95** [comment]
Unfortunately I cannot do this, my company won't allow that.

**Comment by shinyoshiaki** [comment]
By the way, I checked the ffmpeg example in my windows machine. It works wel
![Screenshot (1)](https://user-images.githubusercontent.com/16427740/133981152-a98686f8-6304-4758-b195-f1e81c258f5f.png)
l.

**Comment by SkorpyoN95** [comment]
Maybe Docker is the problem?

**Comment by shinyoshiaki** [comment]
Maybe so. I'm using Windows native FFmpeg.

**Comment by shinyoshiaki** [comment]
Since chrome will soon quit supporting plan-b
I don't think we need to think about plan-b.

**Comment by Canees** [comment]
> Since chrome will soon quit supporting plan-b. I don't think we need to think about plan-b any more.

I think I've found a decent reason why it doesn't work in Win

![image](https://user-images.githubusercontent.com/40012261/176339812-b88d79f0-ab92-41a0-9693-be2fd5838db3.png)
![image](https://user-images.githubusercontent.com/40012261/176339878-77c70a80-8919-40e7-9b3c-9ffbaf0d5cde.png)

Exec is problematic

![image](https://user-images.githubusercontent.com/40012261/176340287-16c5d0ab-b782-4b12-9bb6-12dfea572202.png)
do you understand ?

**Comment by Canees** [comment]
> > Since chrome will soon quit supporting plan-b. I don't think we need to think about plan-b any more.
> 
> I think I've found a decent reason why it doesn't work in Win
> 
> ![image](https://user-images.githubusercontent.com/40012261/176339812-b88d79f0-ab92-41a0-9693-be2fd5838db3.png) ![image](https://user-images.githubusercontent.com/40012261/176339878-77c70a80-8919-40e7-9b3c-9ffbaf0d5cde.png)
> 
> Exec is problematic
> 
> ![image](https://user-images.githubusercontent.com/40012261/176340287-16c5d0ab-b782-4b12-9bb6-12dfea572202.png) do you understand ?

postoptimality：
    exec(`D:/ffmpeg-4.4-full_build/bin/ffmpeg.exe -re -f lavfi -i testsrc=size=640x480:rate=30 -vcodec libvpx -cpu-used 5 -deadline 1 -g 10 -error-resilient 1 -auto-alt-ref 1 -f rtp rtp://127.0.0.1:${port}`,(error, stdout, stderr) => {
      if (error) {
        console.error(`exec error: ${error}`);
        return;
      }
      console.log(`stdout: ${stdout}`);
      console.error(`stderr: ${stderr}`);
    });
