### ISSUE TITLE
mLineIndex regression

### ISSUE THREAD

**Issue by koush** [shinyoshiaki/werift-webrtc#220]
https://github.com/shinyoshiaki/werift-webrtc/commit/32a361047d4bc5898e85ae36a348024e5c5982a7#r75552572

My proposed fix is in that comment.

**Comment by shinyoshiaki** [comment]
If Bundle is enabled, mlineIndex should always be zero, so I fixed it like that PR

**Comment by koush** [comment]
will verify shortly
