### ISSUE TITLE
How to use MediaStream ？

### ISSUE THREAD

**Issue by Canees** [shinyoshiaki/werift-webrtc#229]
hi :
   I saw that the API can use MediaStream addTrack, I want to combine them to get a stream of audio and video，Can you do an example? I tried to do it myself, but it didn't work
   exp:
        
         
![image](https://user-images.githubusercontent.com/40012261/176393447-0ad826bd-70b6-4313-bc7b-3c5cdd16c3f3.png)
![image](https://user-images.githubusercontent.com/40012261/176393498-01244812-fe9e-4b40-a8b6-323cc480b0c2.png)

**Comment by kolserdav** [comment]
> hi : I saw that the API can use MediaStream addTrack, I want to combine them to get a stream of audio and video，Can you do an example? I tried to do it myself, but it didn't work exp:
> 
> ![image](https://user-images.githubusercontent.com/40012261/176393447-0ad826bd-70b6-4313-bc7b-3c5cdd16c3f3.png) ![image](https://user-images.githubusercontent.com/40012261/176393498-01244812-fe9e-4b40-a8b6-323cc480b0c2.png)

How You solve this problem?

**Comment by tigercoxgithub** [comment]
Hi, was this possible?
