### ISSUE TITLE
chrome and android webrtc

### ISSUE THREAD

**Issue by SinLT** [shinyoshiaki/werift-webrtc#241]
![image](https://user-images.githubusercontent.com/20736404/180901881-e5070093-104b-49bd-aaf6-7452624b5b21.png)
![image](https://user-images.githubusercontent.com/20736404/180901905-27662997-ed67-4dec-8de7-53772eba6506.png)
![image](https://user-images.githubusercontent.com/20736404/180902098-2e1796a5-d68c-43c7-9d04-ea675346eae1.png)
When chrome talks with Android webrtc, the Android end cannot receive the stream, and onaddstream has no callback，The onicecandidate of the third figure also does not receive a callback

**Comment by shinyoshiaki** [comment]
Where are you using werift?

**Comment by SinLT** [comment]
> 你在哪里使用 werift？

Use SFU as the node server

**Comment by shinyoshiaki** [comment]
If you can provide me with a minimal amount of code that can reproduce the problem, I can investigate.
