### ISSUE TITLE
New release/how to build develop locally

### ISSUE THREAD

**Issue by oeed** [shinyoshiaki/werift-webrtc#251]
Thanks for merging #249! We need to start using the changes from it, do you have an idea as to when those changes will have an npm release; or alternatively, how to depend on a git version? I'm struggling to build the project locally as its' giving a large number of errors.

**Comment by oeed** [comment]
Alternatively, would a PR to master for the same changes be better?

**Comment by kolserdav** [comment]
Now version `werift` has been updated. But for the future, you can collect your own public npm package.
- Install dependencies in root:
```sh
cd werift-webrtc
npm install
``
- Install dependencies in webrtc:
```sh
cd packages/webrtc
npm install
```
- Change name of package like a:
```json
"name": "@oeed/werift",
```
- Build package
```sh
npm run build
```
- Publish on first time:
```sh
npm publish --access=public
```
- Publish on every other times:
```sh
npm publish 
```

**Comment by oeed** [comment]
Sorry 🤦 I saw in GitHub releases it hadn't been updated, but on npm it has! I should've checked, sorry. Thanks for your help ☺️
