### ISSUE TITLE
Change video constraints on the fly

### ISSUE THREAD

**Issue by kolserdav** [shinyoshiaki/werift-webrtc#273]
We are planning a large number of connections with video tracks. And the more connections, the smaller the size of all videos. How is it possible to change constraints media track on the fly so as not to waste user traffic?

Method `MediaStreamTrack.applyConstraints()` as I see it is not implemented. So I'm wondering if there is a workaround?

**Comment by shinyoshiaki** [comment]
MediaStreamTrack in werift is just a control interface for RTP, so it does not support media control. 
If you want to control the media, please control it on the client (browser or GStreamer or etc...) that is generating the media.
