### ISSUE TITLE
Add unit tests based on web-platform-tests

### ISSUE THREAD

**Issue by shinyoshiaki** [shinyoshiaki/werift-webrtc#53]

**Comment by nimishbhandari** [comment]
i want to work on this issue

**Comment by shinyoshiaki** [comment]
OK!
Tests code is stored under `packages/webrtc/tests`.
`packages/webrtc/tests/peerConnection/addTrack.test.ts` is the test code written based on WPT, so please refer to it.

Please send me a pull request and I will review it.
If you have any questions, please feel free to ask!
