### ISSUE TITLE
Datachannel performance

### ISSUE THREAD

**Issue by ptesavol** [shinyoshiaki/werift-webrtc#55]
Hi, this looks like a very interesting project! 

I was wondering if you have measured the maximum throughput of the data channel? It would be very interesting to know how the performance compares to that of other WebRTC implementations.

**Comment by shinyoshiaki** [comment]
> if you have measured the maximum throughput of the data channel?

not yet.

Do you have measurement records for other implementations ?

**Comment by ptesavol** [comment]
Yes, we created a benchmarking tool node-datachannel that is available at https://github.com/streamr-dev/node-datachannel-performance-diagnostics/tree/main/benchmark There are also some throughput measurement results in the README.md. 

I think with small modifications, our benchmarking scripts could be used for measuring the performance of werift-webrtc as well.

**Comment by shinyoshiaki** [comment]
If you don't mind, could you please write a benchmark code for werift with reference to this example?

https://github.com/shinyoshiaki/werift-webrtc/blob/develop/examples/datachannel/offer.ts
https://github.com/shinyoshiaki/werift-webrtc/blob/develop/examples/datachannel/answer.ts

If you have any questions about how to use werift or how it behaves, please ask.
