### ISSUE TITLE
`dataChannelFlush()` starves sending only one data buffer per entire event loop

### ISSUE THREAD

**Issue by lepsch** [shinyoshiaki/werift-webrtc#59]
The problem is in the following loop of `RTCSctpTransport.dataChannelFlush()` function:

https://github.com/shinyoshiaki/werift-webrtc/blob/ac1328f539336777073a13ad494608be6af452f8/packages/webrtc/src/transport/sctp.ts#L250-L286

My use case is that I call `send` every time the user changes a text in a text-editor. And when I use Werift instead of the [native wrtc package](https://www.npmjs.com/package/wrtc) the other side gets the changes really slowly until the user stops typing. Upon investigating it I've found out that the `this.dataChannelQueue` in this loop increases a lot because `this.sctp.outboundQueue` is always with one item to be sent.

As it turns out, every time a `this.sctp.send` is called inside this loop chunks are immediately added to `this.sctp.outboundQueue` and the loop ends right away. So, it's only going to execute in the next event loop but once again this repeats one by one until the `this.dataChannelQueue` gets empty.

Comparing this function with the reference implementation in [aiortc](https://github.com/aiortc/aiortc/blob/01ff209cc38e887edeb05cba1845cf458b31a0ac/src/aiortc/rtcsctptransport.py#L1640-L1679) they look like the same but there is a fundamental difference between Python AsyncIO and JavaScript Promises. Python AsyncIO enqueue awaitable functions to be run on the next event loop, but [JavaScript Promises runs its executor function synchronously](https://stackoverflow.com/questions/42118900/when-is-the-body-of-a-promise-executed). So, even though the `SCTP.send()` is an async function the code is going to execute synchronously and this function adds chunks to `outboundQueue` and makes the former loop to stop. The loop logic is then flawed in JavaScript as it's going to always dequeue only one item from `dataChannelQueue` and then it stops (Having this `while` loop or just a `if` is the same in JavaScript).

Upon investigating a solution for it the easiest one is to wrap the `SCTP.send()` in a `Promise.resolve.then()` as [JavaScript always enqueue `then` executor functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#timing). Below is the mokey-patch I've made to make it work.

```typescript
    const rtcPeerConnection = new WeriftRTCPeerConnection({ iceServers })

    // Monkey patch `sctp.sctp.send()` to be queued on next event loop otherwise `sctp.dataChannelFlush()` "starves"
    // sending only one buffered data on each event loop
    const createSctpTransport = rtcPeerConnection['createSctpTransport'].bind(rtcPeerConnection)
    rtcPeerConnection['createSctpTransport'] = () => {
      const sctp = createSctpTransport()
      const send = sctp.sctp.send
      sctp.sctp.send = (...args: any[]) => Promise.resolve().then(() => send(...args))
      return sctp
    }
```

With this solution the other side gets the updates much faster but it's not fluid. The other side gets the stream in chunks of text instead of letter by letter. The problem with that solution is that it's going to enqueue everything from `this.dataChannelQueue` not giving any chance to some finished IO waiting in the event loop. It would be nice to have an async `dataChannelFlush` with the loop logic fixed so this would never happen. Also, looks like Werift's `Transport.send` function implementations are not `async` as well so it always halts the entire event loop until the IO finishes.

**Comment by shinyoshiaki** [comment]
It took me a while to notice this ”issue”.
I'll look into it now!

**Comment by shinyoshiaki** [comment]
@lepsch 
I would like to run the code in that developing text editor for debugging purposes, is that possible?
(If you don't want to make it public, you can send it to me via Twitter DM).

**Comment by shinyoshiaki** [comment]
@lepsch 
SCTP tweaked v0.8.6 is now available.
If the problem is still not fixed, please report it.

**Comment by lepsch** [comment]
Nice! Thanks for the quick fix. I haven't had even time to ask for permission to give you the source code I'm working on. Anyway, I'm gonna test it and let you know

**Comment by lepsch** [comment]
Just to confirm that it works like a charm now. As fluid as the [native wrtc](https://www.npmjs.com/package/wrtc).
