### ISSUE TITLE
typo in website tagline: WebRTC -> TypeScript

### ISSUE THREAD

**Issue by jonassmedegaard** [shinyoshiaki/werift-webrtc#61]
The tagline at https://shinyoshiaki.github.io/werift-webrtc/website/build/ says:
> Pure WebRTC implementation of the WebRTC

Seems that's a type, and instead it should instead be this:
> Pure TypeScript implementation of the WebRTC

**Comment by jonassmedegaard** [comment]
...and while at it, I think it is better english to drop "the", like this:
> Pure TypeScript implementation of WebRTC

**Comment by shinyoshiaki** [comment]
thanks!
fixed at https://github.com/shinyoshiaki/werift-webrtc/commit/2b75010c35012951033feaf949faa4e527a15bba
