### ISSUE TITLE
TypeError: Cannot read property 'rtp' of undefined on `setRemoteDescription`

### ISSUE THREAD

**Issue by kindahippoz** [shinyoshiaki/werift-webrtc#72]
I'm currently trying to make a weird media server thing as a little experiment, though I keep getting the following error on `setRemoteDescription`:
```
    at RTCPeerConnection.remoteRtp (/home/MYUSERNAME/code/JS/project/chat/chat/node_modules/werift/lib/webrtc/src/peerConnection.js:382:26)
    at /home/MYUSERNAME/code/JS/project/chat/chat/node_modules/werift/lib/webrtc/src/peerConnection.js:533:37
    at Array.forEach (<anonymous>)
    at RTCPeerConnection.setRemoteDescription (/home/MYUSERNAME/code/JS/project/chat/chat/node_modules/werift/lib/webrtc/src/peerConnection.js:530:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GatewayRTCConnection.answer (/home/MYUSERNAME/code/JS/project/chat/chat/api/v2/gateway/index.js:24:9)
    at async WebSocket.<anonymous> (/home/MYUSERNAME/code/JS/project/chat/chat/api/v2/gateway/index.js:169:37)
```

Here is the serverside handler for getting an offer from the client.

```javascript
let isNewConnection = true;
if (ws.rtc) {
    isNewConnection = false;
} else {
    ws.rtc = new GatewayRTCConnection(ws, this);
}

if (isNewConnection) {
    ws.rtc.connection.onTransceiver.subscribe(async (transceiver) => {
        const [track] = await transceiver.onTrack.asPromise();
        this.inChannel(channel._id, (otherWs) => {
            if (!this.clientRTCReady(otherWs)) return;
            if (otherWs.session.sessionId === ws.session.sessionId) return; // Don't perform the actions below on ourselves

            otherWs.rtc.addTrack(track);
            otherWs.rtc.renegotiate();
        });
    });
}

ws.send(this.packet("EVENT_VOICE_CONNECTION_ANSWER", {
    answer: await ws.rtc.answer(offer)
}));

if (isNewConnection) {
    this.inChannel(channel._id, (otherWs) => {
        if (!this.clientRTCReady(otherWs)) return;
        if (otherWs.session.sessionId === ws.session.sessionId) return; // Don't perform the actions below on ourselves
        
        const otherReceivers = otherWs.rtc.connection.getReceivers();
        for (let i = 0; i < otherReceivers.length; i++) {
            const otherRecevier = otherReceivers[i];
            ws.rtc.addTrack(otherRecevier.tracks[0]);
        }
    });
    ws.rtc.renegotiate();
}
```

This is the small GatewayRTCConnection wrapper I made to simplify the code a little:
```javascript
class GatewayRTCConnection {
    constructor(ws, server) {
        this.ws = ws;
        this.server = server;

        this.connection = new werift.RTCPeerConnection();
        this.connection.onnegotiationneeded.subscribe(() => this.renegotiate);
    }

    async answer(offer) {
        await this.connection.setRemoteDescription(offer);
        await this.connection.setLocalDescription(await this.connection.createAnswer());
        return this.connection.localDescription;
    }

    async addTrack(track) {
        if (!track) return;
        this.connection.addTrack(track);
    }

    async renegotiate() {
        this.ws.send(this.server.packet("EVENT_RENEGOTIATE_REQUIRED", {}));
    }
}
```

I inspected it a little and found that one of the transceivers just does not have an mLineIndex, which is used in `remoteRtp`. I assume it's because I'm adding tracks myself to the connection, but I'm not sure what to do.
Note that it works fine with 2 users, as soon as the new user tries to connect, it generates this error.

**Comment by shinyoshiaki** [comment]
Probably due to the inconsistency between the SDP of the remote Offerer and the Transceiver inside the PeerConnection. Please let me know the information of the remote SDP and Transceivers when the error occurs.

**Comment by kindahippoz** [comment]
Thank you for your response.
The full, latest source for the server can be found here: https://git.hippoz.xyz/hippoz/brainlet
while the full source of the client can be found here: https://git.hippoz.xyz/hippoz/brainlet-react
Let me know if you would like me to mirror this to github though.
Also, I'm not quite sure what you mean by information of sdp and transceiver.

**Comment by shinyoshiaki** [comment]
The cause seems to be an inconsistency between the number of Transceivers in the PeerConnection on the browser side and the number of Transceivers in the PeerConnection on the server side.
In other words, it is caused by the code on the client application side of the browser.

The reason for this problem is that on the server side, addTrack is performed multiple times (as many times as the number of users) to a single PeerConnection, which means that there are as many Transceivers as there are users.
Since brainlet-react is on the Offer side, it is necessary to use addTransceiver to match the number of Transceivers with the server side. (Currently, there is only one Transceiver since client is only doing addTrack once).
