### ISSUE TITLE
Handling of `remoteIsLite` seems incorrect

### ISSUE THREAD

**Issue by wotzlaff** [shinyoshiaki/werift-webrtc#92]
* `iceControlling` is set to `true` in `setLocalDescription` [here](https://github.com/shinyoshiaki/werift-webrtc/blob/develop/packages/webrtc/src/peerConnection.ts#L459-L463) if `this.iceTransport.connection.remoteIsLite` is `true`
* `iceControlling` is set to `true` in `setRemoteDescription` [here](https://github.com/shinyoshiaki/werift-webrtc/blob/develop/packages/webrtc/src/peerConnection.ts#L761-L765) if `media.iceParams?.iceLite` is `true`

The problem is that `remoteIsLite` seems not to be set in the second case. This means that we end up with no controlling agent if we first `setRemoteDescription` and then `setLocalDescription`.

Maybe it is enough to set `remoteIsLite = true` in the second case?

**Comment by shinyoshiaki** [comment]
Thank you for reporting the issue!

I've released a version that fixes this issue.

https://github.com/shinyoshiaki/werift-webrtc/pull/93

https://github.com/shinyoshiaki/werift-webrtc/releases/tag/v0.11.11

**Comment by wotzlaff** [comment]
Thank you for your fast reply. It seems to work now!
